[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "mini-turtle"
version = "0.1.0"
description = "Mini Turtle funcional (adelante, abajo, reiniciar)"
readme = "README.md"
requires-python = ">=3.8"